project:
  type: website
  output-dir: _site
  execute-dir: project
  post-render:
    - touch _site/.nojekyll
website: 
  title: prncevince 
  site-url: https://prncevince.github.io/
  description: ''
  repo-branch: main
  repo-url: https://github.com/prncevince/prncevince.github.io
  page-navigation: true
  navbar:
    right:
      - text: About
        href: about/index.qmd
      - icon: github
        href: https://github.com/prncevince
      - icon: twitter
        href: https://twitter.com/prncevincecares
format: 
  html:
    code-fold: true
    code-link: true
    css: assets/css/style.css
    grid:
      body-width: 1100px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem
    theme: 
      light: [flatly]
      dark: [darkly]
    toc: true
    toc-depth: 6

