project:
  type: website
  output-dir: _site
  execute-dir: project
  render: ["*.qmd", "*.ipynb", "*.md", "*.Rmd", "!notes/"]
  post-render:
    - cp -a resume _site/.
website:
  title: Vincent Clemson
  favicon: /assets/img/favicon.png
  site-url: https://prncevince.io
  description: 'A collection of unique spatial data science content'
  repo-branch: main
  repo-url: https://github.com/prncevince/prncevince.io
  page-navigation: true
  open-graph:
    image: /assets/img/logo-og.png
  twitter-card:
    creator: "@prncevincecares"
    site: "@prncevincecares"
    image: /assets/img/logo-og.png
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about/index.qmd
      - text: "[{{< fa brands github >}}]{class='quarto-navbar-tools-item'}"
        menu:
          - text: GitHub Profile {{< fa brands github-alt >}}
            url:  https://github.com/prncevince
            target: _blank
          - text: Site Source Code 💻
            url:  https://github.com/prncevince/prncevince.io
            target: _blank
          - text: Site Discussions 🗣
            url:  https://github.com/prncevince/prncevince.io/discussions
            target: _blank
      - text: "[{{< fa brands twitter >}}]{class='quarto-navbar-tools-item'}"
        menu:
          - text: News & Science & Code 🚀
            url: https://twitter.com/prncevincecares
            target: _blank
          - text: Sports 🎾
            url: https://twitter.com/prncevincestats
            target: _blank
      - text: "[{{< fa solid rss >}}]{class='rss quarto-navbar-tools-item'}"
        href: posts/index.xml
format:
  html:
    code-fold: true
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    css: [assets/css/style.css]
    grid:
      body-width: 1100px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem
    resources: [assets/img/posts.png]
    template: _pandoc/template.html
    template-partials: [_pandoc/vercel.html, _pandoc/plausible.html]
    theme:
      light: [flatly, 'assets/scss/light.scss']

