project:
  type: website
  output-dir: _site
  execute-dir: project
  render: ["*.qmd", "*.ipynb", "*.md", "*.Rmd", "!notes/"]
  post-render:
    - cp -a resume _site/.
    - touch _site/.nojekyll
website:
  title: Vincent Clemson
  favicon: assets/img/favicon.png
  site-url: https://prncevince.github.io
  description: ''
  repo-branch: main
  repo-url: https://github.com/prncevince/prncevince.github.io
  page-navigation: true
  open-graph: true
  twitter-card:
    creator: "@prncevincecares"
    site: "@prncevincecares"
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about/index.qmd
      - icon: github
        menu:
          - text: GitHub
            url:  https://github.com/prncevince
            target: _blank
          - text: Source Code 💻
            url:  https://github.com/prncevince/prncevince.github.io
            target: _blank
          - text: Discussions 🗣
            url:  https://github.com/prncevince/prncevince.github.io/discussions
            target: _blank
      - icon: twitter
        menu:
          - text: News & Science & Code 🚀
            url: https://twitter.com/prncevincecares
            target: _blank
          - text: Sports 🎾
            url: https://twitter.com/prncevincestats
            target: _blank
format:
  html:
    code-fold: true
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    css: [assets/css/style.css]
    grid:
      body-width: 1100px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem
    theme:
      light: [flatly, 'assets/scss/light.scss']

