project:
  type: website
  output-dir: _site
  execute-dir: project
  render: ["*.qmd", "*.ipynb", "*.Rmd", "*.md", "!SETUP.md", "!LICENSE.md", "!notes/"]
  post-render:
    - cp -a resume _site/.
website:
  title: Vincent Clemson
  favicon: /assets/img/favicon.png
  site-url: https://prncevince.io
  description: 'A collection of unique spatial data science content by Vincent Clemson'
  repo-branch: main
  repo-url: https://github.com/prncevince/prncevince.io
  page-navigation: true
  open-graph:
    image: /assets/img/logo-og.png
  twitter-card:
    creator: "@prncevincecares"
    site: "@prncevincecares"
    image: /assets/img/logo-og.png
  navbar:
    right:
      - text: Posts
        href: posts/index.qmd
      - text: About
        href: about/index.qmd
      - text: "[{{< fa brands github >}}]{class='quarto-navbar-tools-item'}"
        menu:
          - text: GitHub Profile {{< fa brands github-alt >}}
            url:  https://github.com/prncevince
            target: _blank
            rel: me
          - text: Site Discussions 🗣
            url:  https://github.com/prncevince/prncevince.io/discussions
            target: _blank
          - text: Site Source Code 💻
            url:  https://github.com/prncevince/prncevince.io
            target: _blank
      - text: "[{{< fa brands twitter >}}]{class='quarto-navbar-tools-item'}"
        menu:
          - text: News & Science & Code 🚀
            url: https://twitter.com/prncevincecares
            target: _blank
            rel: me
          - text: Sports 🎾
            url: https://twitter.com/prncevincestats
            target: _blank
            rel: me
      - text: "[{{< fa solid rss >}}]{class='rss quarto-navbar-tools-item'}"
        href: posts/index.xml
  page-footer:
    left: |
      [©](/LICENSE.html) 2023 by [Vincent Clemson](/about/) | built with {{< fa solid heart-pulse >}} & Quarto
    center:
      - text: "{{< fa brands twitter >}} {{< fa solid rocket >}}"
        href: https://twitter.com/prncevincecares
        target: _blank
        rel: me
      - icon: linkedin
        href: https://www.linkedin.com/in/vincentclemson/
        target: _blank
        rel: me
        aria-label: My LinkedIn
      - icon: github
        href: https://github.com/prncevince
        target: _blank
        rel: me
      - text: "[{{< fa brands square-instagram >}}]{class='instagram'}"
        href: https://instagram.com/prncemaps/
        target: _blank
        rel: me
      - text: "[{{< fa solid square-rss >}}]{class='rss'}"
        href: posts/index.xml
      - icon: mastodon
        href: https://fosstodon.org/@prncevince
        target: _blank
        rel: me
      - icon: youtube
        href: https://youtube.com/@prncevince
        target: _blank
        rel: me
      - text: "{{< fa brands twitter >}} {{< iconify ph tennis-ball-fill >}}"
        href: https://twitter.com/prncevincestats
        target: _blank
        rel: me
    right: |
      <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0 <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a>
  back-to-top-navigation: true
format:
  html:
    filters:
      - add-code-files
    code-fold: true
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    css: [assets/css/site.css]
    grid:
      body-width: 1100px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem
    resources: [assets/img/posts.png, assets/img/posts-rss.png]
    template: _pandoc/template.html
    template-partials: [_pandoc/vercel.html, _pandoc/plausible.html]
    highlight-style: assets/highlight/zenburn-new.theme
    theme:
      light: [flatly, 'assets/scss/light.scss']

