project:
  type: website
  output-dir: _site
  execute-dir: project
  render: ["*.qmd", "*.ipynb", "*.md", "*.Rmd", "!notes/"]
  post-render:
    - touch _site/.nojekyll
website:
  title: prncevince
  site-url: https://prncevince.github.io
  description: ''
  repo-branch: main
  repo-url: https://github.com/prncevince/prncevince.github.io
  page-navigation: true
  navbar:
    right:
      - text: Blog
        href: posts/index.qmd
      - text: About
        href: about/index.qmd
      - icon: github
        href: https://github.com/prncevince
      - icon: twitter
        href: https://twitter.com/prncevincecares
format:
  html:
    code-fold: true
    code-link: true
    css: [assets/css/style.css]
    grid:
      body-width: 1100px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem
    theme:
      light: [flatly, 'assets/scss/light.scss']
      dark: [darkly, 'assets/scss/dark.scss']
    toc: true
    toc-depth: 6
