name: Publish Site to Vercel
on:
  push:
    branches: [main]
    paths: ['_site/**', '.github/workflows/deploy.yaml', 'vercel.json']
  pull_request:
    branches: [main]
    paths: ['_site/**', '.github/workflows/deploy.yaml', 'vercel.json']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  vercel-deploy:
    runs-on: ${{ matrix.os  }}
    environment:
      name: vercel-production
      url: https://prncevince.xyz
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        node-version: ['lts/*']
        pnpm-version: ['11']
        r-version: ['release']
        r-repo: ['https://cloud.r-project.org']
    # Only runs PR jobs concurrently & uses same group as other vercel- jobs
    # PR jobs run in their own branch & do not deploy anything - so we assume they can run concurrently
    concurrency:
      group: vercel-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      RENV_CONFIG_REPOS_OVERRIDE: ${{ matrix.r-repo }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    # Note: corepack boostraps pnpm via pinned pnpm version via
    #       "packageManager" field of package.json. This is all pnpm setup required.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup/Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable corepack for pnpm Install/Setup 
        run: corepack enable
      - name: Install Node.js dependencies
        run: pnpm i
      - name: Deploy site to Vercel 🚀
        if: github.event_name != 'pull_request'
        run: |
          pnpm vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          pnpm vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          pnpm vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}